(()=>{"use strict";const KEY="eolas-companion-alpha-02",data=window.PALWORLD_DATA,$=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];const defaults={checked:{},lastArea:"Windswept Hills",theme:"north-star",largeText:false,reducedMotion:false,highContrast:false};let state={...defaults,...JSON.parse(localStorage.getItem(KEY)||"{}")};let installPrompt=null;const themes=[{id:"north-star",name:"North Star",note:"Eolas default"},{id:"grove",name:"Grove",note:"Soft green"},{id:"frost",name:"Frost",note:"Cool blue"},{id:"ember",name:"Ember",note:"Warm orange"},{id:"blossom",name:"Blossom",note:"Soft pink"},{id:"night",name:"Night Sky",note:"Deep dark"}];const els={areaSelect:$("#areaSelect"),mapAreaSelect:$("#mapAreaSelect"),markerFilter:$("#markerFilter"),palSearch:$("#palSearch"),palList:$("#palList"),markerList:$("#markerList"),areaProgressLabel:$("#areaProgressLabel"),areaPercent:$("#areaPercent"),areaProgressFill:$("#areaProgressFill"),homeStats:$("#homeStats"),areaCards:$("#areaCards"),progressStats:$("#progressStats"),progressAreas:$("#progressAreas"),journeyArea:$("#journeyArea"),journeyPercent:$("#journeyPercent"),journeyFill:$("#journeyFill"),nextGoals:$("#nextGoals"),themeGrid:$("#themeGrid"),toast:$("#toast"),installButton:$("#installButton")};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));const id=(kind,area,name,type="")=>[kind,area,name,type].join("|");const save=()=>localStorage.setItem(KEY,JSON.stringify(state));const checked=x=>!!state.checked[x];
function applyPrefs(){document.documentElement.dataset.theme=state.theme;document.documentElement.classList.toggle("large-text",state.largeText);document.documentElement.classList.toggle("reduced-motion",state.reducedMotion);document.documentElement.classList.toggle("high-contrast",state.highContrast);$("#largeText").checked=state.largeText;$("#reducedMotion").checked=state.reducedMotion;$("#highContrast").checked=state.highContrast;}
function setup(){const ready=data.areas.filter(a=>data.areaPals[a]);els.areaSelect.innerHTML=ready.map(a=>`<option>${esc(a)}</option>`).join("");els.mapAreaSelect.innerHTML=ready.map(a=>`<option>${esc(a)}</option>`).join("");els.areaSelect.value=ready.includes(state.lastArea)?state.lastArea:ready[0];els.mapAreaSelect.value=els.areaSelect.value;els.markerFilter.innerHTML=data.markerTypes.map(x=>`<option>${esc(x)}</option>`).join("");els.themeGrid.innerHTML=themes.map(t=>`<button class="theme-card ${state.theme===t.id?"selected":""}" data-theme="${t.id}"><i></i><strong>${t.name}</strong><small>${t.note}</small></button>`).join("");$$('[data-theme]').forEach(b=>b.onclick=()=>{state.theme=b.dataset.theme;save();applyPrefs();setup();});}
function pals(area){return data.areaPals[area]||[]}function markers(area){return data.markers[area]||[]}function stats(area){const ps=pals(area),ms=markers(area),pd=ps.filter(n=>checked(id("pal",area,n))).length,md=ms.filter(m=>checked(id("marker",area,m.name,m.type))).length,total=ps.length+ms.length,done=pd+md;return{ps,ms,pd,md,total,done,percent:total?Math.round(done/total*100):0};}
function row(item){const done=checked(item.id);return`<label class="check-row ${done?"done":""}"><input type="checkbox" data-id="${esc(item.id)}" ${done?"checked":""}><span class="custom-check">✓</span><span class="row-copy"><strong>${esc(item.name)}</strong>${item.note?`<small>${esc(item.note)}</small>`:""}</span><span class="tag">${esc(item.tag)}</span></label>`}
function bind(root){$$('input[data-id]',root).forEach(x=>x.onchange=()=>{state.checked[x.dataset.id]=x.checked;save();renderAll();});}
function renderPals(){const area=els.areaSelect.value;state.lastArea=area;els.mapAreaSelect.value=area;save();const q=els.palSearch.value.trim().toLowerCase();const list=pals(area).filter(n=>n.toLowerCase().includes(q));els.palList.innerHTML=list.map(n=>row({id:id("pal",area,n),name:n,tag:"Pal"})).join("")||`<div class="empty-state"><h3>No matches</h3><p>Try another Pal name.</p></div>`;bind(els.palList);const s=stats(area);els.areaProgressLabel.textContent=`${s.pd} of ${s.ps.length} Pals caught`;els.areaPercent.textContent=`${s.percent}% region`;els.areaProgressFill.style.width=s.percent+"%";}
function renderMarkers(){const area=els.mapAreaSelect.value,filter=els.markerFilter.value;state.lastArea=area;els.areaSelect.value=area;save();const list=markers(area).filter(m=>filter==="All"||m.type===filter);els.markerList.innerHTML=list.map(m=>row({id:id("marker",area,m.name,m.type),name:m.name,note:m.note,tag:m.type})).join("")||`<div class="empty-state"><h3>No discoveries in this filter</h3><p>Choose another marker type.</p></div>`;bind(els.markerList);}
function totals(){let total=0,done=0,palTotal=0,palDone=0;Object.keys(data.areaPals).forEach(a=>{const s=stats(a);total+=s.total;done+=s.done;palTotal+=s.ps.length;palDone+=s.pd});return{total,done,palTotal,palDone,percent:total?Math.round(done/total*100):0};}
function stat(v,l){return`<article class="stat-card"><strong>${esc(v)}</strong><span>${esc(l)}</span></article>`}
function renderHome(){const area=state.lastArea,s=stats(area),missingPals=s.ps.filter(n=>!checked(id("pal",area,n))),missingMarkers=s.ms.filter(m=>!checked(id("marker",area,m.name,m.type)));els.journeyArea.textContent=area;els.journeyPercent.textContent=s.percent+"%";els.journeyFill.style.width=s.percent+"%";const goals=[...missingPals.slice(0,2).map(n=>`<div class="goal"><span>⭐</span><div><strong>Catch ${esc(n)}</strong><small>Complete your regional Pal list.</small></div></div>`),...missingMarkers.slice(0,1).map(m=>`<div class="goal"><span>✦</span><div><strong>${esc(m.name)}</strong><small>${esc(m.type)} · ${esc(m.note)}</small></div></div>`)];els.nextGoals.innerHTML=goals.join("")||`<div class="goal"><span>✓</span><div><strong>Region complete</strong><small>Choose your next adventure.</small></div></div>`;const t=totals();els.homeStats.innerHTML=stat(`${t.palDone}/${t.palTotal}`,"Pals caught")+stat(`${s.done}/${s.total}`,`${area} complete`);els.areaCards.innerHTML=data.areas.map(a=>data.areaPals[a]?(()=>{const x=stats(a);return`<button class="area-card" data-area="${esc(a)}"><span><strong>${esc(a)}</strong><small>${x.pd}/${x.ps.length} Pals · ${x.md}/${x.ms.length} discoveries</small></span><span class="mini-progress"><i style="width:${x.percent}%"></i></span><b>${x.percent}%</b></button>`})():`<div class="area-card disabled"><span><strong>${esc(a)}</strong><small>Coming in a future data pack</small></span><b>Soon</b></div>`).join("");$$('[data-area]',els.areaCards).forEach(b=>b.onclick=()=>{els.areaSelect.value=b.dataset.area;state.lastArea=b.dataset.area;switchView("adventureView");renderPals();});}
function renderJourney(){const t=totals();els.progressStats.innerHTML=stat(t.percent+"%","Overall")+stat(`${t.palDone}/${t.palTotal}`,"Pals")+stat(`${t.done-t.palDone}/${t.total-t.palTotal}`,"Discoveries");els.progressAreas.innerHTML=Object.keys(data.areaPals).map(a=>{const s=stats(a);return`<div class="progress-area"><div><strong>${esc(a)}</strong><span>${s.done}/${s.total}</span></div><div class="progress-track"><div style="width:${s.percent}%"></div></div></div>`}).join("");}
function renderAll(){renderPals();renderMarkers();renderHome();renderJourney();}
function switchView(v){$$('.view').forEach(x=>x.classList.toggle('active',x.id===v));$$('.bottom-nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===v));window.scrollTo({top:0,behavior:state.reducedMotion?'auto':'smooth'});if(v==='homeView')renderHome();if(v==='adventureView')renderPals();if(v==='mapView')renderMarkers();if(v==='journeyView')renderJourney();}
$$('.bottom-nav button').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$$('[data-go]').forEach(b=>b.onclick=()=>switchView(b.dataset.go));els.areaSelect.onchange=renderPals;els.mapAreaSelect.onchange=renderMarkers;els.markerFilter.onchange=renderMarkers;els.palSearch.oninput=renderPals;['largeText','reducedMotion','highContrast'].forEach(k=>$("#"+k).onchange=e=>{state[k]=e.target.checked;save();applyPrefs();});
$("#exportButton").onclick=()=>{const blob=new Blob([JSON.stringify({version:"alpha-0.2",exportedAt:new Date().toISOString(),state},null,2)],{type:"application/json"}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='eolas-companion-backup.json';a.click();URL.revokeObjectURL(a.href)};$("#importInput").onchange=async e=>{try{const p=JSON.parse(await e.target.files[0].text());state={...defaults,...p.state};save();applyPrefs();setup();renderAll();toast('Backup imported')}catch{alert('That backup could not be imported.')}};$("#resetButton").onclick=()=>{if(confirm('Reset all Eolas progress on this device?')){state={...defaults,checked:{}};save();applyPrefs();setup();renderAll();toast('Progress reset')}};function toast(m){els.toast.textContent=m;els.toast.classList.remove('hidden');setTimeout(()=>els.toast.classList.add('hidden'),1800)}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;els.installButton.classList.remove('hidden')});els.installButton.onclick=async()=>{if(installPrompt){installPrompt.prompt();await installPrompt.userChoice;installPrompt=null;els.installButton.classList.add('hidden')}};if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('service-worker.js'));applyPrefs();setup();renderAll();})();
