window.PALWORLD_DATA = {
  areas: [
    { name: "Windswept Hills", status: "ready", subtitle: "Starting region" },
    { name: "Marsh Island", status: "planned", subtitle: "Data pack coming soon" },
    { name: "Eastern Wild Island", status: "planned", subtitle: "Data pack coming soon" },
    { name: "Sea Breeze Archipelago", status: "planned", subtitle: "Data pack coming soon" },
    { name: "Ice Wind Island", status: "planned", subtitle: "Data pack coming soon" },
    { name: "Forgotten Island", status: "planned", subtitle: "Data pack coming soon" },
    { name: "Moonless Shore", status: "planned", subtitle: "Data pack coming soon" },
    { name: "Bamboo Groves", status: "planned", subtitle: "Data pack coming soon" },
    { name: "Verdant Brook", status: "planned", subtitle: "Data pack coming soon" },
    { name: "Twilight Dunes", status: "planned", subtitle: "Data pack coming soon" },
    { name: "Mount Obsidian", status: "planned", subtitle: "Data pack coming soon" },
    { name: "Dessicated Desert", status: "planned", subtitle: "Data pack coming soon" },
    { name: "Astral Mountains", status: "planned", subtitle: "Data pack coming soon" },
    { name: "Sakurajima", status: "planned", subtitle: "Data pack coming soon" },
    { name: "Feybreak", status: "planned", subtitle: "Data pack coming soon" },
    { name: "Sunlit Isle", status: "planned", subtitle: "Data pack coming soon" },
    { name: "World Tree", status: "planned", subtitle: "Data pack coming soon" }
  ],
  markerTypes: ["All", "Lifmunk Effigy", "Egg Spawn", "Fast Travel", "Alpha Boss", "Dungeon", "Skill Fruit Tree", "Journal", "Other"],
  areaPals: {
    "Windswept Hills": [
      "Beegarde", "Cattiva", "Chikipi", "Chillet", "Cinnamoth", "Cremis", "Daedream",
      "Dinossom", "Direhowl", "Eikthyrdeer", "Elphidran", "Flopie", "Foxparks",
      "Galeclaw", "Grizzbolt", "Gumoss", "Hoocrates", "Lamball", "Leezpunk",
      "Lifmunk", "Mammorest", "Mossanda", "Pengullet", "Penking", "Robinquill",
      "Tanzee", "Teafant", "Tocotoco", "Vaelet"
    ]
  },
  markers: {
    "Windswept Hills": [
      { type: "Fast Travel", name: "Plateau of Beginnings", note: "240, -513" },
      { type: "Fast Travel", name: "Grassy Behemoth Hills", note: "176, -473" },
      { type: "Fast Travel", name: "Ravine Entrance", note: "-64, -423" },
      { type: "Alpha Boss", name: "Chillet", note: "172, -419" },
      { type: "Alpha Boss", name: "Mammorest", note: "189, -478" }
    ]
  }
,
  palProfiles: {
    "Beegarde": {no:"050",elements:["Grass"],summary:"A worker Pal whose regional entry is still being expanded.",difficulty:"Moderate",obtain:[{type:"Wild / World",detail:"Known to appear in Windswept Hills. Additional acquisition details are still being verified."}],work:[],partner:{name:"Profile in progress",detail:"Partner Skill details are still being verified."},drops:[],why:["Capture it to complete the regional Pal collection"],notes:"Full profile research is still in progress.",progress:["seen","captured","bred","lucky"]},
    "Lamball": {no:"001",elements:["Neutral"],summary:"A gentle early-game worker that supplies Wool and can protect you in a pinch.",difficulty:"Easy",obtain:[{type:"Wild / World",detail:"Common in low-level areas including Windswept Hills; often appears in small groups."},{type:"Dungeon / Boss Realm",detail:"Can appear as the final Alpha in Hillside Cavern."},{type:"Egg",detail:"Hatches from a Common Egg."},{type:"Breeding",detail:"Available through standard breeding."}],work:["Handiwork 1","Transporting 1","Farming 1"],partner:{name:"Fluffy Shield",detail:"Equip Lamball as a shield. At a Ranch, it also produces Wool."},drops:["Wool","Lamball Mutton"],why:["Reliable early Wool source","Useful for simple crafting and hauling","Very easy to find and capture"],notes:"Capture one early, then assign it to a Ranch when you need a steady Wool supply.",progress:["seen","captured","dungeonAlpha","bred","lucky"]},
    "Cattiva": {no:"002",elements:["Neutral"],summary:"A low-cost utility Pal that helps carry resources and covers several early base jobs.",difficulty:"Easy",obtain:[{type:"Wild / World",detail:"Common in Windswept Hills and other beginner regions."},{type:"Dungeon / Boss Realm",detail:"Can appear as the final Alpha in Hillside Cavern."},{type:"Egg",detail:"Hatches from a Common Egg."},{type:"Breeding",detail:"Available through standard breeding."}],work:["Handiwork 1","Gathering 1","Mining 1","Transporting 1"],partner:{name:"Cat Helper",detail:"While in your party, increases carrying capacity. The bonus does not stack in the current version."},drops:["Red Berries"],why:["Extra carry capacity while gathering","Versatile first-base worker","Low food cost"],notes:"Excellent in the opening hours when weight limits and basic base labor are constant friction.",progress:["seen","captured","dungeonAlpha","bred","lucky"]},
    "Chikipi": {no:"003",elements:["Neutral"],summary:"Your earliest renewable Egg producer and a simple Ranch specialist.",difficulty:"Easy",obtain:[{type:"Wild / World",detail:"Common in Windswept Hills and other beginner regions."},{type:"Dungeon / Boss Realm",detail:"Can appear as the final Alpha in Hillside Cavern."},{type:"Egg",detail:"Hatches from a Common Egg."},{type:"Breeding",detail:"Available through standard breeding."}],work:["Gathering 1","Farming 1"],partner:{name:"Egg Layer",detail:"Produces Eggs over time when assigned to a Ranch."},drops:["Egg","Chikipi Poultry"],why:["Renewable Eggs for food and later Cake production","Easy Ranch specialist","Simple early capture"],notes:"Keep at least one at your base if you plan to cook often or begin breeding later.",progress:["seen","captured","dungeonAlpha","bred","lucky"]},
    "Lifmunk": {no:"004",elements:["Grass"],summary:"A flexible early worker with broad base coverage and a weapon-based Partner Skill.",difficulty:"Easy",obtain:[{type:"Wild / World",detail:"Common in Windswept Hills, Sea Breeze Archipelago, Forgotten Island, and part of Bamboo Groves."},{type:"Dungeon / Boss Realm",detail:"Can appear as the final Alpha in Hillside Cavern."},{type:"Egg",detail:"Hatches from a Verdant Egg."},{type:"Breeding",detail:"Available through standard breeding."}],work:["Planting 1","Handiwork 1","Gathering 1","Lumbering 1","Medicine 1"],partner:{name:"Lifmunk Recoil",detail:"With its Pal Gear crafted, Lifmunk rides on your head and fires a submachine gun alongside your attacks."},drops:["Berry Seeds","Low Grade Medical Supplies"],why:["Covers five early base tasks","Useful planting and crafting support","Partner Skill adds burst damage"],notes:"One of the strongest first captures for a new base because it can fill gaps almost anywhere.",progress:["seen","captured","dungeonAlpha","bred","lucky"]},
    "Foxparks": {no:"029",elements:["Fire"],summary:"An accessible source of Kindling and one of the most useful early combat Partner Skills.",difficulty:"Easy",obtain:[{type:"Wild / World",detail:"Common in Windswept Hills, Eastern Wild Island, Forgotten Island, and Scars of War."},{type:"Dungeon / Boss Realm",detail:"Can appear as the final Alpha in Hillside Cavern."},{type:"Egg",detail:"Hatches from a Scorching Egg."},{type:"Breeding",detail:"Available through standard breeding."}],work:["Kindling 1"],partner:{name:"Huggy Fire",detail:"Craft Foxparks's Harness to equip it as a flamethrower. It also provides warmth and light while deployed."},drops:["Leather","Flame Organ"],why:["Runs early cooking and furnaces","Provides Flame Organs","Strong and memorable early Partner Skill"],notes:"A priority capture before you begin smelting regularly. Its single work type also keeps it focused.",progress:["seen","captured","dungeonAlpha","bred","lucky"]},
    "Gumoss": {no:"012",elements:["Grass","Ground"],summary:"A focused planting worker that also improves your personal logging efficiency.",difficulty:"Easy",obtain:[{type:"Wild / World",detail:"Found in Windswept Hills, Sea Breeze Archipelago, Marsh Island, Forgotten Island, and northeastern Bamboo Groves."},{type:"Alpha Boss",detail:"A fixed Alpha appears in Sea Breeze Archipelago around -113, -628."},{type:"Dungeon / Boss Realm",detail:"Can appear as the final Alpha in Hillside Cavern."},{type:"Egg",detail:"Hatches from a Verdant Egg."},{type:"Breeding",detail:"Available through standard breeding."}],work:["Planting 1"],partner:{name:"Logging Assistance",detail:"While in your party, improves logging efficiency and reduces the weight of wood. The current bonus does not stack."},drops:["Berry Seeds","Gumoss Leaf"],why:["Stays focused on Planting","Helps when gathering large amounts of Wood","Rare flower variant has special drops"],notes:"A good choice when multitaskers keep abandoning your berry fields for other work.",progress:["seen","captured","alphaDefeated","dungeonAlpha","bred","lucky"]},
    "Pengullet": {no:"010",elements:["Water","Ice"],summary:"A flexible early utility Pal that can also be obtained through the fishing system.",difficulty:"Easy",obtain:[{type:"Wild / World",detail:"Found near water in several low-level regions."},{type:"Fishing",detail:"Can be caught at saltwater fishing spots, including beginner waters around Sunlit Isle."},{type:"Dungeon / Boss Realm",detail:"May appear in eligible low-level dungeon pools."},{type:"Egg",detail:"Hatches from a Damp or Frozen-type egg depending on current breeding data."},{type:"Breeding",detail:"Available through standard breeding."}],work:["Handiwork 1","Transporting 1","Watering 1","Cooling 1"],partner:{name:"Pengullet Cannon",detail:"Loads Pengullet into a launcher for a powerful shot, at considerable risk to the Pal."},drops:["Ice Organ","Pal Fluids"],why:["Early Watering and Cooling coverage","Can be pursued through fishing","Useful source of Pal Fluids"],notes:"A practical target when you want one Pal to cover several early production needs.",progress:["seen","captured","fished","dungeonAlpha","bred","lucky"]},
    "Chillet": {no:"103",elements:["Ice","Dragon"],summary:"A beloved early Alpha, fast ground-and-water mount, and useful bridge into hotter regions.",difficulty:"Moderate",obtain:[{type:"Wild / World",detail:"Wild Chillet appears in Frostbound Mountains and southern Astral Mountains."},{type:"Alpha Boss",detail:"Fixed Alpha encounter in Windswept Hills around 172, -418."},{type:"Dungeon / Boss Realm",detail:"Can appear as a final Alpha in Astral Mountains Cavern."},{type:"Egg",detail:"Hatches from a Frozen Egg."},{type:"Breeding",detail:"Available through standard breeding."}],work:["Gathering 1","Cooling 2"],partner:{name:"Wriggling Weasel",detail:"Craft the Chillet Saddle at Technology Level 11 to ride it; mounted player attacks become Dragon-type and gain an attack boost."},drops:["Leather","Ancient Civilization Parts (Alpha)","Precious Pelt (Alpha)"],why:["Excellent early mount","Alpha rewards Ancient Civilization Parts","Cooling aura helps approach hot regions","Useful Dragon damage while mounted"],notes:"A strong first Alpha goal once your gear and capture supplies feel comfortable.",progress:["seen","captured","alphaDefeated","dungeonAlpha","bred","lucky"]}
  }
};