window.PALWORLD_DATA = {
  areas: [
    { name: "Windswept Hills", status: "ready", subtitle: "Starting region" },
    { name: "Marsh Island", status: "planned", subtitle: "Data pack coming soon" },
    { name: "Eastern Wild Island", status: "planned", subtitle: "Data pack coming soon" },
    { name: "Sea Breeze Archipelago", status: "planned", subtitle: "Data pack coming soon" },
    { name: "Ice Wind Island", status: "planned", subtitle: "Data pack coming soon" },
    { name: "Forgotten Island", status: "planned", subtitle: "Data pack coming soon" },
    { name: "Moonless Shore", status: "planned", subtitle: "Data pack coming soon" },
    { name: "Bamboo Groves", status: "planned", subtitle: "Data pack coming soon" },
    { name: "Verdant Brook", status: "planned", subtitle: "Data pack coming soon" },
    { name: "Twilight Dunes", status: "planned", subtitle: "Data pack coming soon" },
    { name: "Mount Obsidian", status: "planned", subtitle: "Data pack coming soon" },
    { name: "Dessicated Desert", status: "planned", subtitle: "Data pack coming soon" },
    { name: "Astral Mountains", status: "planned", subtitle: "Data pack coming soon" },
    { name: "Sakurajima", status: "planned", subtitle: "Data pack coming soon" },
    { name: "Feybreak", status: "planned", subtitle: "Data pack coming soon" },
    { name: "Sunlit Isle", status: "planned", subtitle: "Data pack coming soon" },
    { name: "World Tree", status: "planned", subtitle: "Data pack coming soon" }
  ],
  markerTypes: ["All", "Lifmunk Effigy", "Egg Spawn", "Fast Travel", "Alpha Boss", "Dungeon", "Skill Fruit Tree", "Journal", "Other"],
  areaPals: {
    "Windswept Hills": [
      "Beegarde", "Cattiva", "Chikipi", "Chillet", "Cinnamoth", "Cremis", "Daedream",
      "Dinossom", "Direhowl", "Eikthyrdeer", "Elphidran", "Flopie", "Foxparks",
      "Galeclaw", "Grizzbolt", "Gumoss", "Hoocrates", "Lamball", "Leezpunk",
      "Lifmunk", "Mammorest", "Mossanda", "Pengullet", "Penking", "Robinquill",
      "Tanzee", "Teafant", "Tocotoco", "Vaelet"
    ]
  },
  markers: {
    "Windswept Hills": [
      { type: "Fast Travel", name: "Plateau of Beginnings", note: "240, -513" },
      { type: "Fast Travel", name: "Grassy Behemoth Hills", note: "176, -473" },
      { type: "Fast Travel", name: "Ravine Entrance", note: "-64, -423" },
      { type: "Alpha Boss", name: "Chillet", note: "172, -419" },
      { type: "Alpha Boss", name: "Mammorest", note: "189, -478" }
    ]
  }
,
  palProfiles: {
    "Beegarde": {no:"067",elements:["Grass"],stats:{food:"3",hp:"80",attack:"90",defense:"90"},variants:[],summary:"A worker Pal whose regional entry is still being expanded.",difficulty:"Moderate",obtain:[{type:"Wild / World",detail:"Known to appear in Windswept Hills. Additional acquisition details are still being verified."}],work:[],partner:{name:"Profile in progress",detail:"Partner Skill details are still being verified."},drops:[],why:["Capture it to complete the regional Pal collection"],notes:"Full profile research is still in progress.",progress:["seen","captured","bred","lucky"]},
    "Lamball": {no:"001",elements:["Neutral"],stats:{food:"2",hp:"70",attack:"70",defense:"70"},variants:[],summary:"A gentle early-game worker that supplies Wool and can protect you in a pinch.",difficulty:"Easy",obtain:[{type:"Wild / World",detail:"Common in low-level areas including Windswept Hills; often appears in small groups."},{type:"Dungeon / Boss Realm",detail:"Can appear as the final Alpha in Hillside Cavern."},{type:"Egg",detail:"Hatches from a Common Egg."},{type:"Breeding",detail:"Available through standard breeding."}],work:["Handiwork 1","Transporting 1","Farming 1"],partner:{name:"Fluffy Shield",detail:"Equip Lamball as a shield. At a Ranch, it also produces Wool."},drops:["Wool","Lamball Mutton"],why:["Reliable early Wool source","Useful for simple crafting and hauling","Very easy to find and capture"],notes:"Capture one early, then assign it to a Ranch when you need a steady Wool supply.",progress:["seen","captured","dungeonAlpha","bred","lucky"]},
    "Cattiva": {no:"002",elements:["Neutral"],stats:{food:"2",hp:"70",attack:"70",defense:"70"},variants:[],summary:"A low-cost utility Pal that helps carry resources and covers several early base jobs.",difficulty:"Easy",obtain:[{type:"Wild / World",detail:"Common in Windswept Hills and other beginner regions."},{type:"Dungeon / Boss Realm",detail:"Can appear as the final Alpha in Hillside Cavern."},{type:"Egg",detail:"Hatches from a Common Egg."},{type:"Breeding",detail:"Available through standard breeding."}],work:["Handiwork 1","Gathering 1","Mining 1","Transporting 1"],partner:{name:"Cat Helper",detail:"While in your party, increases carrying capacity. The bonus does not stack in the current version."},drops:["Red Berries"],why:["Extra carry capacity while gathering","Versatile first-base worker","Low food cost"],notes:"Excellent in the opening hours when weight limits and basic base labor are constant friction.",progress:["seen","captured","dungeonAlpha","bred","lucky"]},
    "Chikipi": {no:"003",elements:["Neutral"],stats:{food:"1",hp:"60",attack:"60",defense:"60"},variants:[],summary:"Your earliest renewable Egg producer and a simple Ranch specialist.",difficulty:"Easy",obtain:[{type:"Wild / World",detail:"Common in Windswept Hills and other beginner regions."},{type:"Dungeon / Boss Realm",detail:"Can appear as the final Alpha in Hillside Cavern."},{type:"Egg",detail:"Hatches from a Common Egg."},{type:"Breeding",detail:"Available through standard breeding."}],work:["Gathering 1","Farming 1"],partner:{name:"Egg Layer",detail:"Produces Eggs over time when assigned to a Ranch."},drops:["Egg","Chikipi Poultry"],why:["Renewable Eggs for food and later Cake production","Easy Ranch specialist","Simple early capture"],notes:"Keep at least one at your base if you plan to cook often or begin breeding later.",progress:["seen","captured","dungeonAlpha","bred","lucky"]},
    "Lifmunk": {no:"004",elements:["Grass"],stats:{food:"1",hp:"75",attack:"70",defense:"70"},variants:[],summary:"A flexible early worker with broad base coverage and a weapon-based Partner Skill.",difficulty:"Easy",obtain:[{type:"Wild / World",detail:"Common in Windswept Hills, Sea Breeze Archipelago, Forgotten Island, and part of Bamboo Groves."},{type:"Dungeon / Boss Realm",detail:"Can appear as the final Alpha in Hillside Cavern."},{type:"Egg",detail:"Hatches from a Verdant Egg."},{type:"Breeding",detail:"Available through standard breeding."}],work:["Planting 1","Handiwork 1","Gathering 1","Lumbering 1","Medicine 1"],partner:{name:"Lifmunk Recoil",detail:"With its Pal Gear crafted, Lifmunk rides on your head and fires a submachine gun alongside your attacks."},drops:["Berry Seeds","Low Grade Medical Supplies"],why:["Covers five early base tasks","Useful planting and crafting support","Partner Skill adds burst damage"],notes:"One of the strongest first captures for a new base because it can fill gaps almost anywhere.",progress:["seen","captured","dungeonAlpha","bred","lucky"]},
    "Foxparks": {no:"029",elements:["Fire"],stats:{food:"2",hp:"65",attack:"75",defense:"70"},variants:[{name:"Foxparks Cryst",suffix:"Cryst"}],summary:"An accessible source of Kindling and one of the most useful early combat Partner Skills.",difficulty:"Easy",obtain:[{type:"Wild / World",detail:"Common in Windswept Hills, Eastern Wild Island, Forgotten Island, and Scars of War."},{type:"Dungeon / Boss Realm",detail:"Can appear as the final Alpha in Hillside Cavern."},{type:"Egg",detail:"Hatches from a Scorching Egg."},{type:"Breeding",detail:"Available through standard breeding."}],work:["Kindling 1"],partner:{name:"Huggy Fire",detail:"Craft Foxparks's Harness to equip it as a flamethrower. It also provides warmth and light while deployed."},drops:["Leather","Flame Organ"],why:["Runs early cooking and furnaces","Provides Flame Organs","Strong and memorable early Partner Skill"],notes:"A priority capture before you begin smelting regularly. Its single work type also keeps it focused.",progress:["seen","captured","dungeonAlpha","bred","lucky"]},
    "Grizzbolt": {no:"103",elements:["Electric"],stats:{food:"7",hp:"105",attack:"100",defense:"100"},variants:[],summary:"A powerful Electric Pal found naturally at No. 1 Wildlife Sanctuary rather than in the Windswept Hills habitat itself.",difficulty:"Hard",route:{scope:"External capture",fastTravel:"Sea Breeze Archipelago — Castaway Beach",fastTravelCoords:"-99, -711",target:"No. 1 Wildlife Sanctuary",targetCoords:"90, -735",directions:"Teleport to Castaway Beach, mount a flying or swimming Pal, and travel east across the water to the sanctuary. Patrol the island until Grizzbolt appears; it is not guaranteed on every pass.",prep:"The sanctuary is offshore and trespassing can trigger PIDF attention. Bring a water-capable mount or flier, enough spheres for a rare spawn, and room to retreat."},obtain:[{type:"Wildlife Sanctuary",detail:"Natural spawn at No. 1 Wildlife Sanctuary on the southern edge of the map."},{type:"Egg",detail:"Can hatch from a Huge Electric Egg."},{type:"Breeding",detail:"Available through breeding combinations."}],work:["Handiwork 2","Lumbering 2","Transporting 3","Generating Electricity 3"],partner:{name:"Yellow Tank",detail:"Can be ridden and can rapidly fire a minigun while mounted after crafting the required Pal Gear."},drops:["Electric Organ","Leather"],why:["Strong Electric combat option","Excellent electricity and transporting worker","Completes the linked early-game objective"],notes:"This objective is shown with Windswept Hills progress because it is one of your remaining tracked Pals, but the capture route is outside the region.",progress:["seen","captured","bred","lucky"]},
    "Gumoss": {no:"012",elements:["Grass","Ground"],stats:{food:"1",hp:"70",attack:"70",defense:"70"},variants:[],summary:"A focused planting worker that also improves your personal logging efficiency.",difficulty:"Easy",obtain:[{type:"Wild / World",detail:"Found in Windswept Hills, Sea Breeze Archipelago, Marsh Island, Forgotten Island, and northeastern Bamboo Groves."},{type:"Alpha Boss",detail:"A fixed Alpha appears in Sea Breeze Archipelago around -113, -628."},{type:"Dungeon / Boss Realm",detail:"Can appear as the final Alpha in Hillside Cavern."},{type:"Egg",detail:"Hatches from a Verdant Egg."},{type:"Breeding",detail:"Available through standard breeding."}],work:["Planting 1"],partner:{name:"Logging Assistance",detail:"While in your party, improves logging efficiency and reduces the weight of wood. The current bonus does not stack."},drops:["Berry Seeds","Gumoss Leaf"],why:["Stays focused on Planting","Helps when gathering large amounts of Wood","Rare flower variant has special drops"],notes:"A good choice when multitaskers keep abandoning your berry fields for other work.",progress:["seen","captured","alphaDefeated","dungeonAlpha","bred","lucky"]},
    "Pengullet": {no:"010",elements:["Water","Ice"],stats:{food:"2",hp:"70",attack:"75",defense:"70"},variants:[],summary:"A flexible early utility Pal that can also be obtained through the fishing system.",difficulty:"Easy",obtain:[{type:"Wild / World",detail:"Found near water in several low-level regions."},{type:"Fishing",detail:"Can be caught at saltwater fishing spots, including beginner waters around Sunlit Isle."},{type:"Dungeon / Boss Realm",detail:"May appear in eligible low-level dungeon pools."},{type:"Egg",detail:"Hatches from a Damp or Frozen-type egg depending on current breeding data."},{type:"Breeding",detail:"Available through standard breeding."}],work:["Handiwork 1","Transporting 1","Watering 1","Cooling 1"],partner:{name:"Pengullet Cannon",detail:"Loads Pengullet into a launcher for a powerful shot, at considerable risk to the Pal."},drops:["Ice Organ","Pal Fluids"],why:["Early Watering and Cooling coverage","Can be pursued through fishing","Useful source of Pal Fluids"],notes:"A practical target when you want one Pal to cover several early production needs.",progress:["seen","captured","fished","dungeonAlpha","bred","lucky"]},
    "Chillet": {no:"103",elements:["Ice","Dragon"],stats:{food:"3",hp:"90",attack:"80",defense:"80"},variants:[{name:"Chillet Ignis",suffix:"Ignis"}],summary:"A beloved early Alpha, fast ground-and-water mount, and useful bridge into hotter regions.",difficulty:"Moderate",obtain:[{type:"Wild / World",detail:"Wild Chillet appears in Frostbound Mountains and southern Astral Mountains."},{type:"Alpha Boss",detail:"Fixed Alpha encounter in Windswept Hills around 172, -418."},{type:"Dungeon / Boss Realm",detail:"Can appear as a final Alpha in Astral Mountains Cavern."},{type:"Egg",detail:"Hatches from a Frozen Egg."},{type:"Breeding",detail:"Available through standard breeding."}],work:["Gathering 1","Cooling 2"],partner:{name:"Wriggling Weasel",detail:"Craft the Chillet Saddle at Technology Level 11 to ride it; mounted player attacks become Dragon-type and gain an attack boost."},drops:["Leather","Ancient Civilization Parts (Alpha)","Precious Pelt (Alpha)"],why:["Excellent early mount","Alpha rewards Ancient Civilization Parts","Cooling aura helps approach hot regions","Useful Dragon damage while mounted"],notes:"A strong first Alpha goal once your gear and capture supplies feel comfortable.",progress:["seen","captured","alphaDefeated","dungeonAlpha","bred","lucky"]}
    ,"Dinossom": {no:"064",elements:["Grass","Dragon"],stats:{food:"6",hp:"110",attack:"85",defense:"90"},variants:[{name:"Dinossom Lux",suffix:"Lux"}],summary:"A large Grass and Dragon Pal with a linked Electric variant.",difficulty:"Moderate",route:{scope:"Windswept Hills",fastTravel:"Plateau of Beginnings",fastTravelCoords:"240, -513",target:"Wooded slopes in Windswept Hills",targetCoords:"Roaming habitat — no fixed spawn pin",directions:"Teleport to Plateau of Beginnings, then sweep the wooded slopes north and west of the statue. Dinossom can appear alone or as a pair; make a broad loop and return after the habitat refreshes if none appear.",prep:"Bring your strongest practical Pal Spheres and avoid opening with heavy damage; Dinossom is large and easy to over-damage."},obtain:[{type:"Wild / World",detail:"Common roaming habitat in low-level areas including Windswept Hills."},{type:"Dungeon / Boss Realm",detail:"Can appear as the final Alpha in Hillside Cavern."}],work:["Planting 2","Lumbering 2"],partner:{name:"Fragrant Dragon",detail:"Can be ridden after crafting its saddle; mounted attacks deal Grass damage."},drops:["Wheat Seeds"],why:["Planting and Lumbering coverage","Mount utility","Unlocks a connected Lux variant entry"],notes:"Use the capture route below instead of searching the entire region.",progress:["seen","captured","bred","lucky"]},
    "Dinossom Lux": {no:"—",elements:["Electric","Dragon"],stats:{food:"6",hp:"110",attack:"90",defense:"90"},variants:[{name:"Dinossom",suffix:"Base"}],summary:"The Electric variant of Dinossom.",difficulty:"Moderate",obtain:[{type:"Breeding",detail:"A known special breeding result associated with Dinossom and Rayhound."}],work:["Generating Electricity 2","Lumbering 2"],partner:{name:"Thunder Dragon",detail:"Can be ridden; mounted attacks are associated with Electric damage."},drops:["Electric Organ"],why:["Electric work coverage","Variant collection progress","Directly connected to Dinossom"],notes:"Variant links are bidirectional so you can compare related Pals without returning to the list.",progress:["seen","captured","bred","lucky"]},
    "Eikthyrdeer": {no:"—",elements:["Neutral"],stats:{food:"5",hp:"95",attack:"85",defense:"80"},variants:[{name:"Eikthyrdeer Terra",suffix:"Terra"}],summary:"A mobile lumbering Pal with a Ground variant.",difficulty:"Moderate",obtain:[{type:"Wild / World",detail:"Found in woodland and grassland habitats."}],work:["Lumbering 2"],partner:{name:"Guardian of the Forest",detail:"Rideable; can improve lumbering efficiency while mounted."},drops:["Eikthyrdeer Venison","Leather","Horn"],why:["Early mount","Focused lumbering","Linked Terra variant"],notes:"Use the variant chip to open Eikthyrdeer Terra.",progress:["seen","captured","bred","lucky"]},
    "Eikthyrdeer Terra": {no:"—",elements:["Ground"],stats:{food:"5",hp:"95",attack:"90",defense:"85"},variants:[{name:"Eikthyrdeer",suffix:"Base"}],summary:"The Ground variant of Eikthyrdeer.",difficulty:"Moderate",obtain:[{type:"Breeding",detail:"Known special breeding variant associated with Eikthyrdeer and Hangyu."}],work:["Lumbering 2"],partner:{name:"Guardian of the Golden Forest",detail:"Rideable Ground variant."},drops:["Leather","Horn"],why:["Ground element coverage","Variant collection"],notes:"Linked back to its base form.",progress:["seen","captured","bred","lucky"]},
    "Elphidran": {no:"—",elements:["Dragon"],stats:{food:"6",hp:"110",attack:"80",defense:"90"},variants:[{name:"Elphidran Aqua",suffix:"Aqua"}],summary:"A Dragon Pal with a linked Water variant.",difficulty:"Moderate",obtain:[{type:"Wild / World",detail:"Found in designated wildlife habitats and related encounters."}],work:["Lumbering 2"],partner:{name:"Amicable Holy Dragon",detail:"Rideable flying Pal."},drops:["High Quality Pal Oil"],why:["Flying mobility","Dragon coverage","Linked Aqua variant"],notes:"Tap the Aqua variant for its connected entry.",progress:["seen","captured","bred","lucky"]},
    "Elphidran Aqua": {no:"—",elements:["Dragon","Water"],stats:{food:"6",hp:"115",attack:"80",defense:"95"},variants:[{name:"Elphidran",suffix:"Base"}],summary:"The Water and Dragon variant of Elphidran.",difficulty:"Moderate",obtain:[{type:"Breeding",detail:"Known special breeding variant associated with Elphidran and Surfent."}],work:["Lumbering 2","Watering 3"],partner:{name:"Amicable Water Dragon",detail:"Rideable flying variant with Water association."},drops:["High Quality Pal Oil"],why:["Strong Watering coverage","Flying mobility","Variant collection"],notes:"Linked back to Elphidran.",progress:["seen","captured","bred","lucky"]},
    "Leezpunk": {no:"—",elements:["Dark"],stats:{food:"3",hp:"80",attack:"90",defense:"70"},variants:[{name:"Leezpunk Ignis",suffix:"Ignis"}],summary:"A Dark utility Pal with a Fire variant.",difficulty:"Moderate",obtain:[{type:"Wild / World",detail:"Appears in several mid-game habitats."}],work:["Handiwork 1","Gathering 1","Transporting 1"],partner:{name:"Sixth Sense",detail:"Can help reveal nearby dungeon locations."},drops:["Copper Key","Silver Key"],why:["Dungeon-finding utility","Flexible base work","Linked Ignis variant"],notes:"Tap the Ignis variant to compare elements and work roles.",progress:["seen","captured","bred","lucky"]},
    "Leezpunk Ignis": {no:"—",elements:["Fire"],stats:{food:"3",hp:"80",attack:"90",defense:"70"},variants:[{name:"Leezpunk",suffix:"Base"}],summary:"The Fire variant of Leezpunk.",difficulty:"Moderate",obtain:[{type:"Breeding",detail:"Known special breeding variant associated with Leezpunk and Flambelle."}],work:["Kindling 1","Handiwork 1","Gathering 1","Transporting 1"],partner:{name:"Sixth Sense",detail:"Variant utility remains centered on exploration."},drops:["Flame Organ","Silver Key"],why:["Kindling coverage","Exploration utility","Variant collection"],notes:"Linked back to Leezpunk.",progress:["seen","captured","bred","lucky"]},
    "Mammorest": {no:"—",elements:["Grass"],stats:{food:"8",hp:"150",attack:"85",defense:"90"},variants:[{name:"Mammorest Cryst",suffix:"Cryst"}],summary:"A huge Grass Pal and prominent early Alpha encounter.",difficulty:"Hard",obtain:[{type:"Alpha Boss",detail:"Fixed Alpha near Grassy Behemoth Hills around 189, -478."}],work:["Planting 2","Lumbering 2","Mining 2"],partner:{name:"Gaia Crusher",detail:"Rideable; improves lumbering and mining efficiency while mounted."},drops:["High Quality Pal Oil","Leather","Mammorest Meat"],why:["Alpha progression","Broad resource work","Linked Cryst variant"],notes:"The nearby fast travel point is Grassy Behemoth Hills.",progress:["seen","captured","alphaDefeated","bred","lucky"]},
    "Mammorest Cryst": {no:"—",elements:["Ice"],stats:{food:"8",hp:"150",attack:"85",defense:"95"},variants:[{name:"Mammorest",suffix:"Base"}],summary:"The Ice variant of Mammorest.",difficulty:"Hard",obtain:[{type:"Breeding",detail:"Known special breeding variant associated with Mammorest and Wumpo."}],work:["Lumbering 2","Mining 2","Cooling 2"],partner:{name:"Ice Crusher",detail:"Rideable resource-focused variant."},drops:["High Quality Pal Oil","Ice Organ"],why:["Cooling coverage","Resource work","Variant collection"],notes:"Linked back to Mammorest.",progress:["seen","captured","bred","lucky"]},
    "Mossanda": {no:"—",elements:["Grass"],stats:{food:"5",hp:"100",attack:"90",defense:"90"},variants:[{name:"Mossanda Lux",suffix:"Lux"}],summary:"A broad base worker with an Electric variant.",difficulty:"Moderate",obtain:[{type:"Wild / World",detail:"Found in forested mid-game areas."}],work:["Planting 2","Handiwork 2","Lumbering 2","Transporting 3"],partner:{name:"Grenadier Panda",detail:"Can be ridden and use a grenade launcher with the required gear."},drops:["Leather","Mushroom","Tomato Seeds"],why:["Excellent Transporting","Broad base coverage","Linked Lux variant"],notes:"Tap Mossanda Lux for Electric work coverage.",progress:["seen","captured","bred","lucky"]},
    "Mossanda Lux": {no:"—",elements:["Electric"],stats:{food:"5",hp:"100",attack:"100",defense:"90"},variants:[{name:"Mossanda",suffix:"Base"}],summary:"The Electric variant of Mossanda.",difficulty:"Hard",obtain:[{type:"Breeding",detail:"Known special breeding variant associated with Mossanda and Grizzbolt."}],work:["Generating Electricity 2","Handiwork 2","Lumbering 2","Transporting 3"],partner:{name:"Grenadier Panda",detail:"Rideable combat and utility variant."},drops:["Electric Organ","Leather"],why:["Electric generation","Strong transporting","Variant collection"],notes:"Linked back to Mossanda.",progress:["seen","captured","bred","lucky"]},
    "Robinquill": {no:"—",elements:["Grass"],stats:{food:"3",hp:"90",attack:"105",defense:"80"},variants:[{name:"Robinquill Terra",suffix:"Terra"}],summary:"A precise Grass combatant with a Ground variant.",difficulty:"Moderate",obtain:[{type:"Wild / World",detail:"Found in forested habitats."}],work:["Planting 1","Handiwork 2","Gathering 2","Medicine 1","Transporting 2"],partner:{name:"Hawk Eye",detail:"While fighting together, increases damage dealt to enemy weak points."},drops:["Wheat Seeds","Arrow"],why:["Broad base utility","Weak-point combat bonus","Linked Terra variant"],notes:"Tap Robinquill Terra for the Ground version.",progress:["seen","captured","bred","lucky"]},
    "Robinquill Terra": {no:"—",elements:["Grass","Ground"],stats:{food:"3",hp:"90",attack:"105",defense:"85"},variants:[{name:"Robinquill",suffix:"Base"}],summary:"The Grass and Ground variant of Robinquill.",difficulty:"Moderate",obtain:[{type:"Breeding",detail:"Known special breeding variant associated with Robinquill and Fuddler."}],work:["Planting 1","Handiwork 2","Gathering 2","Medicine 1","Transporting 2"],partner:{name:"Hawk Eye",detail:"Retains weak-point combat support."},drops:["Wheat Seeds","Arrow"],why:["Ground coverage","Broad base utility","Variant collection"],notes:"Linked back to Robinquill.",progress:["seen","captured","bred","lucky"]}

  }
};